### ISSUE TITLE
The NintendoSpotPass1 metod dont work whit my 3ds (EUR)

### ISSUE THREAD

**Issue by nicolahey** [MegaPika/Satellazone#20] opened 2024-04-16 11:38 UTC
I jntalled stellazone, and whit fbi work, but when i try the internet connections method it didnt work.
Can you do a europe video tutorial, please?

**Comment by MettleSphee** [comment] 2024-04-16 13:47
You may need to either try or retry a few times, try also doing it without a password if possible.
It doesn't appear instantly, and if it doesn't work after multiple times, you either have it unlocked or there's something wrong with the installed version (if it's still there).

Please reply afterwards.

**Comment by nicolahey** [comment] 2024-04-16 19:26
Hey, i tried it at least 10 times, and not appearing in home menu

**Comment by MettleSphee** [comment] 2024-04-16 23:18
Okay, you should check whether you still have the app installed by trying to access it (or opening it directly) from FBI.
I can't be there physically to actually troubleshoot the problem and solve the issue, so the best I can do is to ask generic questions until I can find the root cause of it.
So after checking if you can open the NZ app from FBI:
- If it's a yes, then I'd ask to make sure that the NZ app is not already on the home menu somewhere (but you should have been notified if a NZ was detected either way)
- If it's a no, then you'd have to force-update/recovery mode the console to re-install the original apps (including NZ, given that your console is EUR, as specified in the title)

If both steps fail, let me know, because there would be something missing from this entire problem that I'd have NO clue how to tackle without proper details.

**Comment by nicolahey** [comment] 2024-04-17 04:50
Hey, i check if there is in the home menu, but i think that if threre is it show me the message that a new software was added,
And sone days ago, i unistalled it from fbi and i was not thinking that i unistalled a system app, so i performed the system update, ant after that in fbi is still nintendo zone visualizer

**Comment by MettleSphee** [comment] 2024-04-17 09:33
Just in case the NZ app has issues or might be corrupted, please use the Recovery Mode to re-install the system apps: https://www.3dbrew.org/wiki/Recovery_Mode
Keep in mind: Any modifications/custom CIAs done to system apps (custom keyboard, home menu, system functionality etc) that are only part of the nintendo system (and not Luma) will be gone, and you may need to reinstall your modifications (if any).

Afterwards, please retry the guide for the NintendoSpotPass1 hotspot as it is written. You may need to wait a bit until it's complete.

Just to test it out on my EUR console with the latest firmware, my console DID connect to the hotspot hosted by me, but didn't recognize the NintendoZone instantly. I entered the settings app, and exited after re-checking the wi-fi settings. I waited around 2-3 minutes, during which somewhere after the first minute I closed the console's lid, let it sit a bit in sleep mode, then re-opened it. It communicated in streetpass mode somehow despite the hotspot not being able to do so, but it recognized the nzone successfully. 
Please respond with the aftermath of this.

**Comment by MettleSphee** [comment] 2024-04-17 09:43
As a side-note, I retried to shutdown the console and start it over, and to keep redoing this close lid and open while hoping it communicates through streetpass after waiting for a bit, the results are somewhat inconsistent, but it does work after a few tries for me, hope it does the same for you!

**Comment by nicolahey** [comment] 2024-04-17 12:43
Hey, i didnt knewed before that i need to use a real hotspot, so it working and showing, thanks!

**Comment by nicolahey** [comment] 2024-04-17 12:44
Hey, do you know how i can trasform my router into a working nintendo zone whit contents?

**Comment by MettleSphee** [comment] 2024-04-17 13:38
> Hey, do you know how i can trasform my router into a working nintendo zone whit contents?

That is not possible at the moment, nor do I know if it will be.
Please close the issue as solved, and if needed, enter the Satellazone discord server to discuss more about such things.

**Closed as completed** 2024-04-17 14:24 UTC
